version: '3.8'

name: parsing

services:

  database:
    container_name: database
    image: postgres:14.2-alpine
    env_file:
      - .docker.db.env
    expose:
      - 5432
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
  admin:
    container_name: admin
    image: parser
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .docker.env
    command:  bash -c "python django_admin/manage.py migrate && python django_admin/manage.py create_superuser_if_not_exists && python django_admin/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - database
    restart: always

  parser:
    container_name: parser
    image: parser
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .docker.env
    command: python src/main.py
    depends_on:
      - database
    restart: always


